services:
  db:
    image: mysql:8
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: microservice
    ports:
      - 3306:3306