openapi: 3.0.3
info:
  title: Microservice
  description: Demonstration of internal microservice architecture
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:3000/{basePath}'
    variables:
      basePath:
        default: "api/v1"
paths:
  /exibillia/{exibilliaID}:
    get:
      description: Get Exibillia by ID
      responses:
        '200':
          description: Exibillia
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/Exibillia'
        '404':
          description: Not found
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      description: Delete Exibillia by ID
      responses:
        '200':
          description: Success
        '500':
          description: Internal error
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /exibillia:
    post:
      description: create new Exibillia
      requestBody:
        $ref: '#/components/schemas/Exibillia'
      responses:
        '200':
          description: Success
        '500':
          description: Internal error
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      description: update Exibillia
      requestBody:
        content:
          application:json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Success
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/Exibillia'
        '404':
          description: Not found
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application:json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Exibillia:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
