// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: v1/exibillia.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExibilliaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetExibilliaRequest) Reset() {
	*x = GetExibilliaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExibilliaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExibilliaRequest) ProtoMessage() {}

func (x *GetExibilliaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExibilliaRequest.ProtoReflect.Descriptor instead.
func (*GetExibilliaRequest) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{0}
}

func (x *GetExibilliaRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExibilliaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exibillia *Exibillia `protobuf:"bytes,1,opt,name=exibillia,proto3" json:"exibillia,omitempty"`
}

func (x *GetExibilliaResponse) Reset() {
	*x = GetExibilliaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExibilliaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExibilliaResponse) ProtoMessage() {}

func (x *GetExibilliaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExibilliaResponse.ProtoReflect.Descriptor instead.
func (*GetExibilliaResponse) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{1}
}

func (x *GetExibilliaResponse) GetExibillia() *Exibillia {
	if x != nil {
		return x.Exibillia
	}
	return nil
}

type CreateExibilliaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CreateExibilliaRequest) Reset() {
	*x = CreateExibilliaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExibilliaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExibilliaRequest) ProtoMessage() {}

func (x *CreateExibilliaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExibilliaRequest.ProtoReflect.Descriptor instead.
func (*CreateExibilliaRequest) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExibilliaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExibilliaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExibilliaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateExibilliaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateExibilliaResponse) Reset() {
	*x = CreateExibilliaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExibilliaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExibilliaResponse) ProtoMessage() {}

func (x *CreateExibilliaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExibilliaResponse.ProtoReflect.Descriptor instead.
func (*CreateExibilliaResponse) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{3}
}

func (x *CreateExibilliaResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateExibilliaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *UpdateExibilliaRequest) Reset() {
	*x = UpdateExibilliaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExibilliaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExibilliaRequest) ProtoMessage() {}

func (x *UpdateExibilliaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExibilliaRequest.ProtoReflect.Descriptor instead.
func (*UpdateExibilliaRequest) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateExibilliaRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExibilliaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExibilliaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteExibilliaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteExibilliaRequest) Reset() {
	*x = DeleteExibilliaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExibilliaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExibilliaRequest) ProtoMessage() {}

func (x *DeleteExibilliaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExibilliaRequest.ProtoReflect.Descriptor instead.
func (*DeleteExibilliaRequest) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteExibilliaRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Exibillia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Exibillia) Reset() {
	*x = Exibillia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_exibillia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exibillia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exibillia) ProtoMessage() {}

func (x *Exibillia) ProtoReflect() protoreflect.Message {
	mi := &file_v1_exibillia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exibillia.ProtoReflect.Descriptor instead.
func (*Exibillia) Descriptor() ([]byte, []int) {
	return file_v1_exibillia_proto_rawDescGZIP(), []int{6}
}

func (x *Exibillia) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exibillia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exibillia) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exibillia) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Exibillia) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Exibillia) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_v1_exibillia_proto protoreflect.FileDescriptor

var file_v1_exibillia_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x78,
	0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x35, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x09, 0x65, 0x78, 0x69,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x22, 0x62, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xdb, 0x01, 0x0a, 0x09, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xcf, 0x02,
	0x0a, 0x10, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x69, 0x62,
	0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45,
	0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x57, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x69, 0x62, 0x69,
	0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x24, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x69, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x15, 0x5a, 0x13, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_exibillia_proto_rawDescOnce sync.Once
	file_v1_exibillia_proto_rawDescData = file_v1_exibillia_proto_rawDesc
)

func file_v1_exibillia_proto_rawDescGZIP() []byte {
	file_v1_exibillia_proto_rawDescOnce.Do(func() {
		file_v1_exibillia_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_exibillia_proto_rawDescData)
	})
	return file_v1_exibillia_proto_rawDescData
}

var file_v1_exibillia_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_exibillia_proto_goTypes = []interface{}{
	(*GetExibilliaRequest)(nil),     // 0: microservice.GetExibilliaRequest
	(*GetExibilliaResponse)(nil),    // 1: microservice.GetExibilliaResponse
	(*CreateExibilliaRequest)(nil),  // 2: microservice.CreateExibilliaRequest
	(*CreateExibilliaResponse)(nil), // 3: microservice.CreateExibilliaResponse
	(*UpdateExibilliaRequest)(nil),  // 4: microservice.UpdateExibilliaRequest
	(*DeleteExibilliaRequest)(nil),  // 5: microservice.DeleteExibilliaRequest
	(*Exibillia)(nil),               // 6: microservice.Exibillia
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_v1_exibillia_proto_depIdxs = []int32{
	6, // 0: microservice.GetExibilliaResponse.exibillia:type_name -> microservice.Exibillia
	7, // 1: microservice.Exibillia.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: microservice.Exibillia.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: microservice.ExibilliaService.Get:input_type -> microservice.GetExibilliaRequest
	2, // 4: microservice.ExibilliaService.Create:input_type -> microservice.CreateExibilliaRequest
	4, // 5: microservice.ExibilliaService.Update:input_type -> microservice.UpdateExibilliaRequest
	5, // 6: microservice.ExibilliaService.Delete:input_type -> microservice.DeleteExibilliaRequest
	1, // 7: microservice.ExibilliaService.Get:output_type -> microservice.GetExibilliaResponse
	3, // 8: microservice.ExibilliaService.Create:output_type -> microservice.CreateExibilliaResponse
	8, // 9: microservice.ExibilliaService.Update:output_type -> google.protobuf.Empty
	8, // 10: microservice.ExibilliaService.Delete:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_exibillia_proto_init() }
func file_v1_exibillia_proto_init() {
	if File_v1_exibillia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_exibillia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExibilliaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_exibillia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExibilliaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_exibillia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExibilliaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_exibillia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExibilliaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_exibillia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExibilliaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_exibillia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExibilliaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_exibillia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exibillia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_exibillia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_exibillia_proto_goTypes,
		DependencyIndexes: file_v1_exibillia_proto_depIdxs,
		MessageInfos:      file_v1_exibillia_proto_msgTypes,
	}.Build()
	File_v1_exibillia_proto = out.File
	file_v1_exibillia_proto_rawDesc = nil
	file_v1_exibillia_proto_goTypes = nil
	file_v1_exibillia_proto_depIdxs = nil
}
