connections:
  db:
    user: root
    password: rootpasswd
    addr: localhost:3306
    name: microservice

  kafka:
    brokers: localhost:29092
    group_name: microservice-1

cron:
  jarklin.send_new_events: "* * * * *"